# Generated by Django 3.0.8 on 2020-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorDataModel',
            fields=[
                ('AdvisorId', models.AutoField(primary_key=True, serialize=False)),
                ('AdvisorName', models.CharField(max_length=50)),
                ('AdvisorPhotoURL', models.URLField()),
            ],
        ),
    ]
