# Generated by Django 3.0.8 on 2020-07-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
