# Generated by Django 3.0.8 on 2020-07-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorAPI', '0003_auto_20200727_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDataModel',
        ),
    ]
