# Generated by Django 3.0.8 on 2020-07-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0001_initial'),
        ('AdvisorAPI', '0004_delete_userdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorBookingModel',
            fields=[
                ('BookingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingTime', models.DateTimeField()),
                ('AdvisorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdvisorAPI.AdvisorDataModel')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAPI.UserModel')),
            ],
        ),
    ]
